---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  # Adds the per-environment DNS name to the database's LoadBalancer Service.
  - path: database.yaml

# TODO: Deploy patch too
#   - path: backend.yaml
