---
app:
  log_level: debug
  port: 8080
  read_header_timeout_seconds: 2
  read_timeout_seconds: 5
  write_timeout_seconds: 5
  idle_timeout_seconds: 30

postgres:
  timeouts:
    acquire_timeout_ms: 500
    query_timeout_ms: 2000
  # Per API pod. Postgres allows 100 connections (a few reserved)
  pool:
    min_conns: 5
    max_conns: 20

redis:
  timeouts:
    query_timeout_ms: 500
