---
app:
  log_level: debug
  port: 8080
  read_header_timeout_seconds: 2
  read_timeout_seconds: 5
  write_timeout_seconds: 5
  idle_timeout_seconds: 30

postgres:
  timeouts:
    acquire_timeout_ms: 100
    query_timeout_ms: 2000
  pool:
    min_conns: 10
    max_conns: 50

redis:
  timeouts:
    query_timeout_ms: 500
