apiVersion: builtin
kind: AnnotationsTransformer
metadata:
  name: deploy-annotations
annotations:
  grncunha.com/git-repository: https://github.com/GilbertoCunha/system-design
  grncunha.com/git-commit: c39231981bf034c0140f681a7b50344757938dab

fieldSpecs:
  - path: metadata/annotations
    create: true
