apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
images:
- name: url-shortener-backend
  newName: ghcr.io/gilbertocunha/system-design
  newTag: url-shortener-backend-47d936e2e44d29c3fbc9444ce1ebac2fca47a94d
