---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: url-shortener-api
spec:
  template:
    spec:
      containers:
        - name: api
          image: ghcr.io/gilbertocunha/system-design:url-shortener-backend-31df3f7afd1fa0e1e540d799223459663b99a248
          command:
            - /bin/url_shortener
            - --environment
            - prod
          # Prevent privilege escalation
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
          env:
            - name: REDIS_URI
              value: redis://url-shortener-cache:6379
            - name: POSTGRES_URI
              valueFrom:
                secretKeyRef:
                  name: url-shortener-db-app
                  key: uri
          # Define expected resources for the pods
          resources:
            requests:
              cpu: 200m
              memory: 100Mi
            limits:
              cpu: 500m
              memory: 200Mi
          # Define readiness and liveness conditions
          # using probes
          readinessProbe:
            initialDelaySeconds: 2
            periodSeconds: 5
            httpGet:
              path: /healthz
              port: 8080
          livenessProbe:
            periodSeconds: 10
            httpGet:
              path: /healthz
              port: 8080
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: url-shortener
spec:
  parentRefs:
    - name: gw-public
      namespace: gateway-system
      sectionName: http
  hostnames:
    - url-shortener.grncunha.com
