apiVersion: builtin
kind: AnnotationsTransformer
metadata:
  name: deploy-annotations
annotations:
  grncunha.com/git-repository: https://github.com/GilbertoCunha/system-design
  grncunha.com/git-commit: 7d80928a2d0bd4856dae4ba3a5cb06e50960e6c3
  app.kubernetes.io/version: v0.2.0
fieldSpecs:
  - path: metadata/annotations
    create: true
