// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Url struct {
	ID        int64
	ShortUrl  string
	LongUrl   string
	CreatedAt pgtype.Timestamptz
}
