// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cleanOldUrls = `-- name: CleanOldUrls :exec
DELETE FROM urls
WHERE created_at < $1
`

func (q *Queries) CleanOldUrls(ctx context.Context, createdAt pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, cleanOldUrls, createdAt)
	return err
}

const getLongUrl = `-- name: GetLongUrl :one
SELECT long_url FROM urls
WHERE short_url = $1
`

func (q *Queries) GetLongUrl(ctx context.Context, shortUrl string) (string, error) {
	row := q.db.QueryRow(ctx, getLongUrl, shortUrl)
	var long_url string
	err := row.Scan(&long_url)
	return long_url, err
}

const putShortUrl = `-- name: PutShortUrl :exec
INSERT INTO urls (
  short_url, long_url
) VALUES (
  $1, $2
)
`

type PutShortUrlParams struct {
	ShortUrl string
	LongUrl  string
}

func (q *Queries) PutShortUrl(ctx context.Context, arg PutShortUrlParams) error {
	_, err := q.db.Exec(ctx, putShortUrl, arg.ShortUrl, arg.LongUrl)
	return err
}
