---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: url-shortener-backend
spec:
  template:
    spec:
      containers:
        - name: url-shortener
          command:
            - /bin/url_shortener
            - --environment
            - prod
