---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: url-shortener-backend
  labels:
    app: url-shortener
    role: backend
spec:
  replicas: 2
  # Spread pods across nodes
  topologySpreadConstraints:
    - topologyKey: kubernetes.io/hostname
      maxSkew: 1
      whenUnsatisfiable: DoNotSchedule
  selector:
    matchLabels:
      app: url-shortener
      role: backend
  template:
    metadata:
      labels:
        app: url-shortener
        role: backend
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        runAsGroup: 65534
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: api
          image: ghcr.io/gilbertocunha/system-design:url-shortener-backend-939cdf42f5944855ee697ef0115eaa2069503109
          # Prevent privilege escalation
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
          env:
            - name: POSTGRES_URI
              valueFrom:
                secretKeyRef:
                  name: url-shortener-db-app
                  key: uri
          # Define expected resources for the pods
          resources:
            requests:
              cpu: 200m
              memory: 100Mi
            limits:
              cpu: 500m
              memory: 200Mi
          # Define readiness and liveness conditions
          # using probes
          readinessProbe:
            initialDelaySeconds: 2
            periodSeconds: 5
            httpGet:
              path: /healthz
              port: 8080
          livenessProbe:
            periodSeconds: 10
            httpGet:
              path: /healthz
              port: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: url-shortener-backend
  labels:
    app: url-shortener
    role: backend
spec:
  type: ClusterIP
  selector:
    app: url-shortener
    role: backend
  ports:
    - name: 8080-8080
      port: 8080
      protocol: TCP
      targetPort: 8080
