---
apiVersion: builtin
kind: AnnotationsTransformer
metadata:
  name: git-annotations
annotations:
  grncunha.com/git-repository: https://github.com/GilbertoCunha/system-design
  grncunha.com/git-commit: f1f449cb2e1b16d3c041a523a35854ca422ffbba
fieldSpecs:
  - path: metadata/annotations
    create: true
