---
apiVersion: builtin
kind: AnnotationsTransformer
metadata:
  name: git-annotations
annotations:
  grncunha.com/git-repository: https://github.com/GilbertoCunha/system-design
  grncunha.com/git-commit: eb281989b5dd4098e1c762905730f86e1967c070
fieldSpecs:
  - path: metadata/annotations
    create: true
